[package]
name = "carcassone"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.26", features = ["derive"] }
clipboard-rs = "0.2.2"
ggez = "0.9.3"
lazy_static = "1.5.0"
rand = "0.8.5"
serde = "1.0.217"
slotmap = "1.0.7"
